/**
 * Represents the severity of an alert.
 */
export enum AlertSeverity {
    Low = 'low',
    Medium = 'medium',
    High = 'high',
}

/**
 * Represents the status of an alert.
 */
export enum AlertStatus {
    Open = 'open',
    InProgress = 'in-progress',
    Closed = 'closed',
}

/**
 * Represents a single alert generated by a rule.
 */
export interface Alert {
    id: string;
    ruleId: string;
    transactionId: string;
    timestamp: string; // ISO 8601 date string
    severity: AlertSeverity;
    status: AlertStatus;
    assigneeId?: string; // User ID
}
