/**
 * Represents a single alert generated by a rule.
 */
export interface Alert {
  id: string;
  ruleId: string;
  transactionId: string;
  timestamp: string; // ISO 8601 date string
  severity: 'low' | 'medium' | 'high';
  status: 'open' | 'in-progress' | 'closed';
  assigneeId?: string; // User ID
}